name: CI
on:
  workflow_dispatch:
env:
  DOTNET_NOLOGO: true
jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          #- os: windows-2019
          #  name: Windows
          - os: ubuntu-20.04
            name: Linux
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install SQL Server (Windows)
        if: matrix.name == 'Windows'
        #TODO: investigate caching
        run: |
          choco install sql-server-express
          echo "::set-output name=credentials_args::"
          echo "::set-output name=db_instance::.\SQLEXPRESS"
      - name: Start SQL Server (Linux)
        id: server
        if: matrix.name == 'Linux'
        run: |
          docker run -d -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=DEVELOPERSdevelopers" -p 1433:1433 mcr.microsoft.com/mssql/server:2019-latest
          echo '::set-output name=credentials_args::-U "sa" -P "DEVELOPERSdevelopers"'
          echo "::set-output name=db_instance::localhost"
      - name: Setup SQL Server
        run: |
          #Invoke-Sqlcmd -Query "CREATE DATABASE nservicebus" -ServerInstance ".\SQLEXPRESS"
          #Invoke-Sqlcmd -Query "CREATE DATABASE nservicebus1" -ServerInstance ".\SQLEXPRESS"
          #Invoke-Sqlcmd -Query "CREATE DATABASE nservicebus2" -ServerInstance ".\SQLEXPRESS"
          #Invoke-Sqlcmd -Query "CREATE SCHEMA receiver AUTHORIZATION db_owner" -ServerInstance $db_instance -Database "nservicebus" $credentials_args
          #Invoke-Sqlcmd -Query "CREATE SCHEMA sender AUTHORIZATION db_owner" -ServerInstance $db_instance -Database "nservicebus" $credentials_args
          #Invoke-Sqlcmd -Query "CREATE SCHEMA db@ AUTHORIZATION db_owner" -ServerInstance $db_instance -Database "nservicebus" $credentials_args
          echo "start setup"
          $db_instance = ${{ steps.server.outputs.db_instance }}
          $credentials_args = ${{ steps.server.outputs.credentials_args }}
          echo "db_instance: $db_instance"
          sqlcmd -Q "CREATE DATABASE nservicebus" -S $db_instance
          sqlcmd -Q "CREATE DATABASE nservicebus1" -S $db_instance
          sqlcmd -Q "CREATE DATABASE nservicebus2" -S $db_instance
          sqlcmd -Q "CREATE SCHEMA receiver AUTHORIZATION db_owner" -S $db_instance -d "nservicebus" $credentials_args
          sqlcmd -Q "CREATE SCHEMA sender AUTHORIZATION db_owner" -S $db_instance -d "nservicebus" $credentials_args
          sqlcmd -Q "CREATE SCHEMA db@ AUTHORIZATION db_owner" -S $db_instance -d "nservicebus" $credentials_args
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - name: Setup .NET Core 3.1 runtime
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x
      - name: Build
        run: dotnet build src --configuration Release
      - name: Run tests
        uses: Particular/run-tests-action@v1.0.0
